default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: format-terraform
        name: format-terraform
        entry: bash -c "terraform fmt -recursive"
        language: system
        require_serial: true
      - id: validate-terraform-prd
        name: validate-terraform-prd
        entry: .pre-commit/terraform_validate.sh infra/terraform/prd
        language: script
