default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 23.9.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_validate
      - id: terraform_fmt
        args:
          - --args=-write=true
      - id: terraform_tflint
        args:
          - --args=--module
      - id: terraform_providers_lock
        args:
          - --args=-platform=darwin_arm64
          - --hook-config=--mode=only-check-is-current-lockfile-cross-platform
